# <center>Alkalmazott Analízis II.</center>

## <center>Fekete Imre</center>
### <center>Alkalmazott Analízis és Számításmatematikai Tanszék</center>
<img src="cimer2.jpg" width="400">
<br>
<br>
<br>
<br>

### Általános információk:
+ <span class="fa fa-building-o"></span> Déli Tömb 3.702</li>
+ Honlap: <a href="http://imrefekete.web.elte.hu/" target="_blank"> http://imrefekete.web.elte.hu/</a>
+ Fogadóórák:  később lesz hivatalos (megbeszélés alapján) 
+ Piazza: Kurzushoz kapcsolódó minden anyag és csoportos levelezés: <a href="piazza.com/elte.hu/fall2019/na3">regisztrációs link</a>
<br><br>

### Számonkérés:
+ 1 db zárthelyi
+ Csoportos projekt (3 fő) 
    + Irodalmi feldolgozás és programozási megvalósítás
    + TeX-ben részletes report írása 
    + Prezentáció (egyik gyakorlaton, mely kb. 10 perc)
+ Beadható feladatokkal lehet bónuszpontokat szerezni
<br><br>

### Segédanyagok:
+ Előadás jegyzete
+ <a href="http://tankonyvtar.ttk.bme.hu/authorlistp.jsp?bookId=30">Faragó István, Horváth Róbert: Numerikus módszerek </a>
+ <a href="http://tankonyvtar.ttk.bme.hu/authorlistp.jsp?bookId=117"> Faragó István, Fekete Imre, Horváth Róbert: Numerikus módszerek példatár </a>
<br><br>

### 3 kívánság:

<br>
<br>


<div style="width:870 px"></div>
<div style="float:left"><img src="questions.jpg" width="450" title="Nyugodtan kérdezzünk!"/></div>
<div style="float:left"><img src="practice.jpg" width="400" title="Sokat gyakoroljunk/dolgozzunk otthon!"/></div>
<div style="float:left"><img src="positive.jpg" width="870" title="A jó hangulat sokat segít!"/></div> 
<div style="clear:both"></div> 
<br><br>


### Miről lesz szó a félév során?
<br>
<br>


<div style="width:600 px">
<div style="float:left"><img src="iterativesolvers.png" width="450" title="Jacobi, GS és SOR iterációs módszerek konvergenciája"/></div>
<div style="float:left"><img src="rkstab.png" width="270" title="RK stabilitási tartományok"/></div>
<div style="float:left"><img src="2dlaplace.png" width="400" title="2D-s Laplace diszkretizációja"/></div> 
<div style="clear:both"></div>
</div>   


<br>
<br>
## <center>1. Feladatsor</center>


### LAER direkt megoldási módszerei
#### Gauss-elimináció

1.feladat. Oldjuk meg az alábbi egyenletrendszereket!

\begin{alignat*}{11}
  \ \ \ \ \ 3x_1 &+{} & x_2 &+{} & 6x_3 &={} & 2 &\quad\ \ \ \ \  \ \ \ \  &-4x_1 &+{} &  x_2 &-{} &  x_3 &={} &  -9 \\
  \ (a) \ \ \ 2x_1 &+{} & x_2 &+{} & 3x_3 &={} & 3 &\quad\ \ \ \ \ \ (b)\ \  & -x_1 &+{} & 4x_2 &-{} &  x_3 &={} & -12\\
  \ \ \ \ \ x_1 &+{}&  x_2 &+{} &  x_3 &={} & -1 &\quad\ \ \ \ \ \ \ \ \  & x_1 &+{} &  x_2 &+{} & 4x_3 &={} &  11
\end{alignat*}

2.feladat. Oldjuk meg Gauss-eliminációval a következõ rendszereket!
<br>
<br>
$(a)\left(
  \begin{array}{ccc}
 2 & 1 & 1\\
 4 & 1 & 0 \\
 -2 & 2 & 1\end{array} \right)
\left(
  \begin{array}{c}
 x_1\\
 x_2\\
 x_3\end{array} \right)
$=$\left(
  \begin{array}{c}
 1\\
 -2\\
 7\end{array} \right)
$
&nbsp;&nbsp;&nbsp;
$(b)\left(
  \begin{array}{ccc}
 2 & 4 & 1\\
 2 & 6 & -1 \\
 1 & 5 & 2\end{array} \right)
\left(
  \begin{array}{c}
 x_1\\
 x_2\\
 x_3\end{array} \right)
$=$\left(
  \begin{array}{c}
 4\\
 10\\
 2\end{array} \right)
$



3.feladat. Végrehajtható-e a Gauss-algoritmus a tanult tételek alapján? (Válaszunkat indokuljuk!)
<br>
<br>

$(a)\left(
  \begin{array}{ccc}
 1 & 2 & 5\\
 2 & 1 & 3 \\
 5 & 3 & 4\end{array} \right)
$&nbsp;&nbsp;&nbsp;
$(b)\left(
  \begin{array}{ccc}
 8 & -1 & -2\\
 0 & 1 & 0 \\
 0 & -3 & 10\end{array} \right)
$&nbsp;&nbsp;&nbsp;
$(c)\left(
  \begin{array}{ccc}
 -2 & 3 & 4\\
 -4 & 6 & 1 \\
 -8 & -2 & 3\end{array} \right)
$
<br>
<br>

In [2]:
% 1.feladat 
A_1=[3 1 6; 2 1 3; 1 1 1]; b_1=[2 3 -1]'; x1=A_1\b_1;
A_2=[-4 1 -1; -1 4 -1; 1 1 4]; b_2=[-9 -12 11]'; x2=A_2\b_2;

In [3]:
A=[1 2 5; 2 1 3; 5 3 4]; %all(eig(A) > eps)
eig(A)
det(A)

ans =

  -2.73406
  -0.55146
   9.28552

ans =  14.000


In [9]:
A=[8 -1 -2; 0 1 0; 0 -3 10];
det(A(1:2,1:2))
det(A)

ans =  8
ans =  80


In [7]:
A=[-2 3 4; -4 6 1; -8 -2 3];
eig(A)
det(A(1:2,1:2))
det(A)

ans =

   0.85042 + 6.02194i
   0.85042 - 6.02194i
   5.29916 + 0.00000i

ans = 0
ans =  196


<br>
4.feladat. Adjunk elégséges feltételt arra, hogy egy szigorúan diagonálisan domináns mátrix M-mátrix legyen!
<br><br>

#### LU-felbontás

5.feladat. Írjuk fel az 1. és 2. feladatokban szereplõ egyenletrendszerek mátrixainak $LU$-felbontását és számoljuk ki a determinánsait! Oldjuk meg a feladatokat az $LU$-felbontás segítségével.

6.feladat. Van-e $LU$-felbontása az alábbi mátrixoknak?

$(a) \left(
  \begin{array}{cc}
 1 & 2\\
 1 & 2\end{array} \right)
$
&nbsp;&nbsp;&nbsp;
$(b) \left(
  \begin{array}{cc}
 0 & 1\\
 1 & 0\end{array} \right)
$
&nbsp;&nbsp;&nbsp;
$(c) \left(
  \begin{array}{cc}
 0 & 1\\
 0 & 2\end{array} \right)
$

<br>
<br>

In [1]:
A=[2 1 1; 4 1 0; -2 2 1];
[L,U,P] = lu(A);
L=[1 0 0; 2/3 1 0; 1/3 2 1]
U=[3 1 6; 0 1/3 -1; 0 0 1]
rats(L)
L*U

L =

   1.00000   0.00000   0.00000
   0.66667   1.00000   0.00000
   0.33333   2.00000   1.00000

U =

   3.00000   1.00000   6.00000
   0.00000   0.33333  -1.00000
   0.00000   0.00000   1.00000

ans =

          1          0          0
        2/3          1          0
        1/3          2          1

ans =

   3   1   6
   2   1   3
   1   1   1



7.feladat. Az alábbi szimmetrikus mátrixok közül melyek pozitív definitek?

$(a) \left(
  \begin{array}{ccc}
 1 & 1 & 1\\
 1 & 3 & -1 \\
 1 & -1 & 5\end{array} \right)
$
&nbsp;&nbsp;&nbsp;
$(b) \left(
  \begin{array}{ccc}
 1 & 1 & 1\\
 1 & 3 & -1 \\
 1 & -1 & -2\end{array} \right)
$
&nbsp;&nbsp;&nbsp;
$(c)\left(
  \begin{array}{ccc}
 2 & -1 & 0\\
 -1 & 2 & -1 \\
 0 & -1 & 2\end{array} \right)
$

8.feladat. Bizonyítsuk be, hogy pozitív definit mátrix főátlójában pozitív elemek állnak!<br>

9.feladat. Bizonyítsuk be, hogy ha $A\in\mathbb{R}^{n\times n}$ szimmetrikus, pozitív definit mátrix, akkor a sajátértékei (valósak és) pozitívak! Mutassuk meg, hogy az ilyen mátrixoknak van inverze!<br>

10.feladat. Igazoljuk, hogy $L^{-1}_i(v_i)=L_i(-v_i)$!

In [87]:
A=[1 2 3; 4 5 6; 7 8 9];
for i=1:length(A)
    v(i)=det(A(1:i,1:i)); % bal felső sarokdetermináns
end
any(v>0) % pozitívak-e ezek 1:igen; 0:nem

ans =

     1


#### PLU- és Cholesky-felbontás
<br>
<br>

11.feladat. Adjuk meg a 
<center>
$\left(
  \begin{array}{cccc}
 0 & 0 & 1 & 1\\
 2 & 2 & 2 & 2\\
 1 & 2 & 1 & 2\\
 2 & 4 & 1 & 1\end{array} \right)
$
</center>
mátrix $PLU$-felbontását!



In [1]:
A=[0 0 1 1; 2 2 2 2; 1 2 1 2; 2 4 1 1]
[L,U,P]=lu(A)

A =

   0   0   1   1
   2   2   2   2
   1   2   1   2
   2   4   1   1

L =

   1.00000   0.00000   0.00000   0.00000
   1.00000   1.00000   0.00000   0.00000
   0.00000   0.00000   1.00000   0.00000
   0.50000   0.50000   0.50000   1.00000

U =

   2   2   2   2
   0   2  -1  -1
   0   0   1   1
   0   0   0   1

P =

Permutation Matrix

   0   1   0   0
   0   0   0   1
   1   0   0   0
   0   0   1   0



12.feladat. Ellenőrizzük, hogy az alábbi mátrixok szimmetrikus pozitív definitek és számítsuk ki a Cholesky-felbontásukat az $LU$-felbontásainak segítségével!
<br>
<br>
$(a) \left(
  \begin{array}{ccc}
 5 & 7 & 3\\
 7 & 11 & 2\\
 3 & 2 & 6\end{array} \right)
$
&nbsp;&nbsp;&nbsp;
$(b) \left(
  \begin{array}{cccc}
 1 & 2 & 3 & 9\\
 2 & 8 & 10 & 34\\
 3 & 10 & 17 & 57\\
 9 & 34 & 57 & 195\end{array} \right)
$

13.feladat. Ellenőrizzük, hogy az alábbi mátrixok szimmetrikus pozitív definitek és számítsuk ki a Cholesky-felbontásukat a gyökvonásos algoritmus segítségével!
<br>
<br>
$(a) \left(
  \begin{array}{ccc}
 5 & 0 & -1\\
 0 & 6 & 1\\
 -1 & 1 & 6\end{array} \right)
$
&nbsp;&nbsp;&nbsp;
$(b) \left(
  \begin{array}{ccc}
 2 & -1 & 0\\
 -1 & 2 & -1\\
 0 & -1 & 2\end{array} \right)
$

In [2]:
A=[5 7 3; 7 11 2; 3 2 6]
chol(A,'lower') %chol help chol(A,'lower'); chol(A,'upper')


A =

    5    7    3
    7   11    2
    3    2    6

ans =

  2889/1292          0          0
  6765/2161  5291/4830          0
   1292/963   -966/481  1960/4801



In [12]:
N=10;
e=ones(N,1);
A=spdiags([-e 2*e -e],[-1 0 1],N,N);
eig(A)
lambda1=min(eig(A))
lambdan=max(eig(A))
opt=2/(lambda1+lambdan)

ans =

   0.081014
   0.317493
   0.690279
   1.169170
   1.715370
   2.284630
   2.830830
   3.309721
   3.682507
   3.918986

lambda1 =  0.081014
lambdan =  3.9190
opt =  0.50000


In [4]:
 2889/1292

ans =  2.2361


In [5]:
sqrt(5)

ans =  2.2361
